version: '3.1'

services:
  springboot:
    build: .
    restart: always
    container_name: springboot
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo/simulacao-venda
  mongo:
    image: mongo:4.0.4
    container_name: springboot-mongo
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always